/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class syncleus_dann_Neuron */

#ifndef _Included_syncleus_dann_Neuron
#define _Included_syncleus_dann_Neuron
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     syncleus_dann_Neuron
 * Method:    nativeConstructor
 * Signature: (Lsyncleus_dann/Layer;Lsyncleus_dann/DNA;D)I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Neuron_nativeConstructor
  (JNIEnv *, jobject, jobject, jobject, jdouble);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    nativeDestructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Neuron_nativeDestructor
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    GetOutput
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_syncleus_dann_Neuron_GetOutput
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    GetDNA
 * Signature: ()Lsyncleus_dann/DNA;
 */
JNIEXPORT jobject JNICALL Java_syncleus_dann_Neuron_GetDNA
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    GetDeltaTrain
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_syncleus_dann_Neuron_GetDeltaTrain
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    GetParentLayer
 * Signature: ()Lsyncleus_dann/Layer;
 */
JNIEXPORT jobject JNICALL Java_syncleus_dann_Neuron_GetParentLayer
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    ConnectToNeuron
 * Signature: (Lsyncleus_dann/Neuron;D)Z
 */
JNIEXPORT jboolean JNICALL Java_syncleus_dann_Neuron_ConnectToNeuron
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    DisconnectAllDestinationSynapses
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Neuron_DisconnectAllDestinationSynapses
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    DisconnectAllSourceSynapses
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Neuron_DisconnectAllSourceSynapses
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    DisconnectAllSynapses
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Neuron_DisconnectAllSynapses
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    DisconnectSourceSynapse
 * Signature: (Lsyncleus_dann/Synapse;)Z
 */
JNIEXPORT jboolean JNICALL Java_syncleus_dann_Neuron_DisconnectSourceSynapse
  (JNIEnv *, jobject, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    DisconnectDestinationSynapse
 * Signature: (Lsyncleus_dann/Synapse;)Z
 */
JNIEXPORT jboolean JNICALL Java_syncleus_dann_Neuron_DisconnectDestinationSynapse
  (JNIEnv *, jobject, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    GetOutgoingConnectionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Neuron_GetOutgoingConnectionCount
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    GetIncommingConnectionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Neuron_GetIncommingConnectionCount
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    Propogate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_syncleus_dann_Neuron_Propogate
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    SetNeuronInput
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Neuron_SetNeuronInput
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    ResetNeuronInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Neuron_ResetNeuronInput
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    BackPropogateWeight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Neuron_BackPropogateWeight
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    BackPropogateStructure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Neuron_BackPropogateStructure
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Neuron
 * Method:    SetTrainingData
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Neuron_SetTrainingData
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
