/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class syncleus_dann_Layer */

#ifndef _Included_syncleus_dann_Layer
#define _Included_syncleus_dann_Layer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     syncleus_dann_Layer
 * Method:    getSourceLayer
 * Signature: ()Lsyncleus_dann/Layer;
 */
JNIEXPORT jobject JNICALL Java_syncleus_dann_Layer_getSourceLayer
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    getDestinationLayer
 * Signature: ()Lsyncleus_dann/Layer;
 */
JNIEXPORT jobject JNICALL Java_syncleus_dann_Layer_getDestinationLayer
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    nativeConstructor
 * Signature: (Lsyncleus_dann/NeuralNet;Lsyncleus_dann/DNA;Lsyncleus_dann/Layer;Lsyncleus_dann/Layer;)I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Layer_nativeConstructor
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    nativeDestructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_nativeDestructor
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    GetNeuralNet
 * Signature: ()Lsyncleus_dann/NeuralNet;
 */
JNIEXPORT jobject JNICALL Java_syncleus_dann_Layer_GetNeuralNet
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    AddNeurons
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_AddNeurons
  (JNIEnv *, jobject, jint);

/*
 * Class:     syncleus_dann_Layer
 * Method:    AddNeuron
 * Signature: (Lsyncleus_dann/Neuron;)V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_AddNeuron
  (JNIEnv *, jobject, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    ConnectAllToLayer
 * Signature: (Lsyncleus_dann/Layer;)V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_ConnectAllToLayer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    ConnectAllToNextLayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_ConnectAllToNextLayer
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    ConnectAllToForwardLayers
 * Signature: (Lsyncleus_dann/Layer;)V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_ConnectAllToForwardLayers
  (JNIEnv *, jobject, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    GetRandomNeuron
 * Signature: ()Lsyncleus_dann/Neuron;
 */
JNIEXPORT jobject JNICALL Java_syncleus_dann_Layer_GetRandomNeuron
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    GetNeuronByUid
 * Signature: (I)Lsyncleus_dann/Neuron;
 */
JNIEXPORT jobject JNICALL Java_syncleus_dann_Layer_GetNeuronByUid
  (JNIEnv *, jobject, jint);

/*
 * Class:     syncleus_dann_Layer
 * Method:    ContainsNeuronByUid
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_syncleus_dann_Layer_ContainsNeuronByUid
  (JNIEnv *, jobject, jint);

/*
 * Class:     syncleus_dann_Layer
 * Method:    NeuronCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Layer_NeuronCount
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    OutgoingConnectionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Layer_OutgoingConnectionCount
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    IncommingConnectionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Layer_IncommingConnectionCount
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    MaximumOutgoingConnectionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Layer_MaximumOutgoingConnectionCount
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    MinimumOutgoingConnectionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Layer_MinimumOutgoingConnectionCount
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    MaximumIncommingConnectionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Layer_MaximumIncommingConnectionCount
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    MinimumIncommingConnectionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_syncleus_dann_Layer_MinimumIncommingConnectionCount
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    GetOutput
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_syncleus_dann_Layer_GetOutput
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    PropogateAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_PropogateAll
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    SetInput
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_SetInput
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     syncleus_dann_Layer
 * Method:    SetTrainData
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_SetTrainData
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     syncleus_dann_Layer
 * Method:    BackPropogateWeightAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_BackPropogateWeightAll
  (JNIEnv *, jobject);

/*
 * Class:     syncleus_dann_Layer
 * Method:    BackPropogateStructureAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_syncleus_dann_Layer_BackPropogateStructureAll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
