/*
 * ImagePanel.java
 *
 * Created on August 22, 2008, 9:47 PM
 */
package com.syncleus.core.dann.examples.nci.ui;
import java.awt.Graphics;
import java.awt.Image;


/**
 *
 * @author  Administrator
 */
public class ImagePanel extends javax.swing.JPanel
{
    private Image image = null;
    
    
    /** Creates new form ImagePanel */
    public ImagePanel()
    {
        initComponents();
    }
    
    public void setImage(Image newImage)
    {
        this.image = newImage;
        this.repaint();
    }
    
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        if(this.image != null)
            g.drawImage(this.image, 0, 0, this);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
